# Generated by Django 3.2.18 on 2023-10-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_alter_preprintaccess_options'),
        ('merritt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merrittjobstatus',
            name='preprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.preprint'),
        ),
        migrations.AlterField(
            model_name='preprintmerrittrequests',
            name='preprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.preprint'),
        ),
    ]
